[package]
name = "winget-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "winget"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
winget-core = { version = "0.1.0", path = "../winget-core" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_Console"] }
